name: al_baker_air_conditioning

description: >-
  A Flutter project for Elbakr Air Conditioning. This app provides user registration,
  login, product browsing, and ordering features, powered by a backend API.

publish_to: "none" # Remove or change to 'https://pub.dev' if publishing publicly.

# -----------------------------------------------------------------------------
# VERSIONING
# -----------------------------------------------------------------------------
# Format: major.minor.patch+build
# * major – Breaking changes
# * minor – New features, but backwards‑compatible
# * patch – Backwards‑compatible bug fixes
# * build – Internal build number for stores (Android/iOS/Windows)
# Update with:
#   flutter build --build-name <x.y.z> --build-number <n>
version: 1.0.0+1

# -----------------------------------------------------------------------------
# ENVIRONMENT
# -----------------------------------------------------------------------------
environment:
  sdk: ">=3.7.2 <4.0.0" # Ensure compatibility with Dart 3.7.x.

# -----------------------------------------------------------------------------
# DEPENDENCIES
# -----------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8        # iOS‑style icons
  lottie: ^3.3.1                 # Lottie animations
  cached_network_image: ^3.3.0   # Network images with caching

  # Network & storage
  dio: ^5.8.0+1                  # HTTP client
  shared_preferences: ^2.0.15    # Local key‑value storage

  # Utils
  url_launcher: ^6.2.4           # Open URLs in browser / apps
  rflutter_alert: ^2.0.7         # Stylish alert dialogs (Arabic messages)


  ionicons: ^0.2.2
  intl: ^0.20.2
# -----------------------------------------------------------------------------
# DEV DEPENDENCIES
# -----------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0          # Recommended lint rules
  flutter_launcher_icons: ^0.14.3 # Auto‑generate adaptive launcher icons

# -----------------------------------------------------------------------------
# FLUTTER CONFIGURATION
# -----------------------------------------------------------------------------
flutter:
  uses-material-design: true

  # ASSETS --------------------------------------------------------------------
  assets:
    - lib/screens/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animations/

  # FONTS ---------------------------------------------------------------------
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Light.ttf   # weight 400
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf    # weight 700
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf # weight 800
          weight: 800

# -----------------------------------------------------------------------------
# FLUTTER LAUNCHER ICONS CONFIG
# Run `flutter pub run flutter_launcher_icons:main` to generate icons.
# -----------------------------------------------------------------------------
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon4.png
  remove_alpha_ios: true



# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package